hardware = {
    # Start PC
    "start_pc": {
        "mainboard": "Zero MX One",
        "cpu": ["CoreOne A100"],
        "processorCooler": ["CPU Cooler Mini"],
        "gpu": [],
        "ram": ["Crossfire One"],
        "disk": ["HDD Elements Zero A"],
        "powerPack": "Crossfire XSOne 500 Watt",
        "case": "Mini-ITX",
    },
    # ----- Mainboards -----
    "mainboard": {
        # Start Mainboard
        "Zero MX One": {
            "case": "Mini-ITX",
            "cpuSocket": "XT2019",
            "cpuSlots": 1,
            "coreTemperatureControl": False,
            "usbPorts": 0,
            "ram": {"ramSlots": 1, "maxRamSize": 128, "ramTyp": [("DDR", 1)], "frequency": [422]},
            "graphicUnitOnBoard": {"name": "nForce 1", "ramSize": 128, "frequency": 322},
            "expansionSlots": [{"interface": ("AGP", 1), "interfaceSlots": 1}],
            "diskStorage": {"diskSlots": 2, "interface": [("IDE", 1)]},
            "networkPort": {"name": "LAN Megabit Ethernet", "interface": "RJ45", "speed": 100},
            "power": 10,
        },
        "Zero MX Pro": {
            "case": "Mini-ATX",
            "cpuSocket": "XT2019",
            "cpuSlots": 1,
            "coreTemperatureControl": False,
            "usbPorts": 1,
            "ram": {"ramSlots": 1, "maxRamSize": 1024, "ramTyp": [("DDR", 1)], "frequency": [922, 1122]},
            "graphicUnitOnBoard": {"name": "nForce 1", "ramSize": 128, "frequency": 322},
            "expansionSlots": [{"interface": ("AGP", 1), "interfaceSlots": 1}],
            "diskStorage": {"diskSlots": 2, "interface": [("IDE", 1)]},
            "networkPort": {"name": "LAN Megabit Ethernet", "interface": "RJ45", "speed": 100},
            "power": 15,
        },
        "Zetta Ultimate M150": {
            "case": "Mini-ATX",
            "cpuSocket": "XT2020",
            "cpuSlots": 1,
            "coreTemperatureControl": False,
            "usbPorts": 2,
            "ram": {
                "ramSlots": 2,
                "maxRamSize": 2048,
                "ramTyp": [("DDR", 1), ("DDR", 2)],
                "frequency": [922, 1222, 1422],
            },
            "graphicUnitOnBoard": None,
            "expansionSlots": [{"interface": ("PCI", 1), "interfaceSlots": 1}],
            "diskStorage": {"diskSlots": 2, "interface": [("SATA", 1)]},
            "networkPort": {"name": "LAN Gigabit Ethernet", "interface": "RJ45", "speed": 1000},
            "power": 20,
        },
        "Zeus Professional X2": {
            "case": "ATX",
            "cpuSocket": "XT2021",
            "cpuSlots": 1,
            "coreTemperatureControl": False,
            "usbPorts": 2,
            "ram": {"ramSlots": 2, "maxRamSize": 4096, "ramTyp": [("DDR", 2), ("DDR", 3)], "frequency": [1422, 1622]},
            "graphicUnitOnBoard": None,
            "expansionSlots": [{"interface": ("PCI", 2), "interfaceSlots": 1}],
            "diskStorage": {"diskSlots": 3, "interface": [("SATA", 1), ("SATA", 3)]},
            "networkPort": {"name": "LAN Gigabit Ethernet", "interface": "RJ45", "speed": 1000},
            "power": 20,
        },
        "Zeus Professional X3": {
            "case": "ATX",
            "cpuSocket": "XT2021",
            "cpuSlots": 1,
            "coreTemperatureControl": False,
            "usbPorts": 2,
            "ram": {
                "ramSlots": 2,
                "maxRamSize": 8192,
                "ramTyp": [("DDR", 3), ("DDR", 4)],
                "frequency": [1622, 1800, 2400],
            },
            "graphicUnitOnBoard": None,
            "expansionSlots": [
                {"interface": ("PCI", 2), "interfaceSlots": 1},
                {"interface": ("PCIe", 3), "interfaceSlots": 1},
            ],
            "diskStorage": {"diskSlots": 3, "interface": [("SATA", 1), ("SATA", 3)]},
            "networkPort": {"name": "LAN Gigabit Ethernet", "interface": "RJ45", "speed": 1000},
            "power": 20,
        },
    },
    # ----- Processor -----
    "cpu": {
        # Start CPU
        "CoreOne A100": {
            "frequencyMin": 500,
            "frequencyMax": 500,
            "socket": "XT2019",
            "cores": 1,
            "turboSpeed": False,
            "overClock": False,
            "maxTemperature": 72,
            "graphicUnit": None,
            "power": 220,
        },
        # Single Core
        "CoreOne A110": {
            "frequencyMin": 800,
            "frequencyMax": 800,
            "socket": "XT2019",
            "cores": 1,
            "turboSpeed": False,
            "overClock": False,
            "maxTemperature": 72,
            "graphicUnit": None,
            "power": 240,
        },
        # Dual Core
        "DualCore M101": {
            "frequencyMin": 800,
            "frequencyMax": 800,
            "socket": "XT2020",
            "cores": 2,
            "turboSpeed": False,
            "overClock": False,
            "maxTemperature": 72,
            "graphicUnit": {"name": "HD Graphic 100", "ramSize": 512, "frequency": 522},
            "power": 250,
        },
        # Quad Core
        "QuadCore TX900": {
            "frequencyMin": 2200,
            "frequencyMax": 2200,
            "socket": "XT2021",
            "cores": 4,
            "turboSpeed": False,
            "overClock": False,
            "maxTemperature": 92,
            "graphicUnit": {"name": "HD Graphic 110", "ramSize": 1024, "frequency": 522},
            "power": 210,
        },
        "QuadCore TX950": {
            "frequencyMin": 3000,
            "frequencyMax": 3000,
            "socket": "XT2021",
            "cores": 4,
            "turboSpeed": False,
            "overClock": False,
            "maxTemperature": 92,
            "graphicUnit": {"name": "HD Graphic 115", "ramSize": 1024, "frequency": 922},
            "power": 230,
        },
    },
    # ----- ProcessorCooler -----
    "processorCooler": {
        "CPU Cooler Mini": {"coolerSpeed": 1, "socket": "XT2019", "power": 10},
        "CPU Cooler Plus": {"coolerSpeed": 2, "socket": "XT2020", "power": 10},
        "CPU Cooler Pro": {"coolerSpeed": 4, "socket": "XT2021", "power": 15},
    },
    # ----- RAM -----
    "ram": {
        # Start RAM
        "Crossfire One": {"ramSize": 128, "ramTyp": ("DDR", 1), "frequency": 422, "power": 5},
        "Crossfire ZX100": {"ramSize": 512, "ramTyp": ("DDR", 1), "frequency": 922, "power": 5},
        "Crossfire ZX110": {"ramSize": 1024, "ramTyp": ("DDR", 1), "frequency": 922, "power": 10},
        "Crossfire ZX120": {"ramSize": 1024, "ramTyp": ("DDR", 1), "frequency": 1122, "power": 10},
        "Crossfire ZX200": {"ramSize": 1024, "ramTyp": ("DDR", 2), "frequency": 1222, "power": 10},
        "Crossfire ZX210": {"ramSize": 1024, "ramTyp": ("DDR", 2), "frequency": 1422, "power": 10},
        "Crossfire ZX220": {"ramSize": 2048, "ramTyp": ("DDR", 3), "frequency": 1622, "power": 10},
        "Crossfire P50": {"ramSize": 4096, "ramTyp": ("DDR", 4), "frequency": 1800, "power": 10},
        "Crossfire P60": {"ramSize": 4096, "ramTyp": ("DDR", 4), "frequency": 2400, "power": 10},
    },
    # ----- Graphic cards -----
    "gpu": {
        # Start GPU
        "Forcevid MX1000": {
            "ramSize": 512,
            "ramTyp": ("GDDR", 1),
            "frequency": 422,
            "interface": ("AGP", 1),
            "power": 80,
        },
        "Zetta TX2066": {
            "ramSize": 1024,
            "ramTyp": ("GDDR", 1),
            "frequency": 1200,
            "interface": ("PCI", 1),
            "power": 220,
        },
        "Zetta TX2066 Pro": {
            "ramSize": 2048,
            "ramTyp": ("GDDR", 2),
            "frequency": 1444,
            "interface": ("PCI", 2),
            "power": 280,
        },
    },
    # ----- Disks -----
    "disk": {
        # Start Disk
        "HDD Elements Zero A": {
            "diskTyp": "HDD",
            "capacity": 2000,
            "writingSpeed": 8,
            "readingSpeed": 16,
            "interface": ("IDE", 1),
            "power": 15,
        },
        "HDD Elements Zero B": {
            "diskTyp": "HDD",
            "capacity": 5000,
            "writingSpeed": 15,
            "readingSpeed": 25,
            "interface": ("IDE", 1),
            "power": 15,
        },
        "HDD Elements Two": {
            "diskTyp": "HDD",
            "capacity": 10000,
            "writingSpeed": 60,
            "readingSpeed": 80,
            "interface": ("SATA", 1),
            "power": 15,
        },
        "SSD 20GB MX": {
            "diskTyp": "SSD",
            "capacity": 20000,
            "writingSpeed": 150,
            "readingSpeed": 200,
            "interface": ("SATA", 3),
            "power": 6,
        },
        "SSD 100GB M.2": {
            "diskTyp": "SSD",
            "capacity": 100000,
            "writingSpeed": 1500,
            "readingSpeed": 1800,
            "interface": ("PCIe", 3),
            "power": 5,
        },
    },
    # ----- PowerPack -----
    "powerPack": {"Crossfire XSOne 500 Watt": {"totalPower": 500}, "Zeus X10 Pro": {"totalPower": 700}},
    # ----- Case -----
    "case": ["Mini-ITX", "Mini-ATX", "ATX"],
}
